# Generated by Django 4.2.15 on 2024-08-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohortinfo',
            name='location',
        ),
        migrations.AddField(
            model_name='cohortinfo',
            name='campus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
